
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/andreburgaud/crypt2go"

[[constraint]]
  branch = "master"
  name = "github.com/rs/zerolog"

[[constraint]]
  name = "github.com/dgraph-io/badger"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-multierror"

[[constraint]]
  branch = "master"
  name = "github.com/jrick/bitset"

[[constraint]]
  name = "github.com/pierrec/lz4"
  version = "1.1.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/satori/go.uuid"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/tvdburgt/go-argon2"

[[constraint]]
  branch = "master"
  name = "github.com/tyler-smith/go-bip39"

[[constraint]]
  name = "github.com/willf/bloom"
  version = "2.0.3"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "zombiezen.com/go/capnproto2"
  version = "2.17.0"
